version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 6000:6000
    volumes:
      - ./:/opt/app
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: