apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-challenge-deployment
spec:
  selector:
    matchLabels:
      app: challenge
  template:
    metadata:
      labels:
        app: challenge
    spec:
      containers:
      - name: my-challenge-container
        image: my-challenge-image
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6000

---
apiVersion: v1
kind: Service
metadata:
  name: challenge
spec:
  type: LoadBalancer
  selector:
    app: challenge
  ports:
  - port: 6000
    targetPort: 6000